services:
    depends_on:
      - server
  server:
    build:
      context: .
    ports:
      - 5421:5421
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/megatron
  db:
    image: postgres
    restart: always
  ms-api-gateway:
    build:
      context: ms-api-gateway
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./ms-api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ms-get
      - ms-post
      - ms-put
      - ms-delete
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=megatron
      - POSTGRES_USER=megatron
      - POSTGRES_PASSWORD=megatron
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "megatron" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: {}